language: python

python:
    - "2.7"

before_install:
    - pip install nose
    - pip install coverage
    - pip install coveralls

install: "pip install -r requirements.txt --use-mirrors"

before_script:
    - psql -c "CREATE ROLE flashcube WITH LOGIN PASSWORD 'd4t41slava!';" -U postgres
    - psql -c 'CREATE DATABASE flashcube_testing WITH OWNER flashcube;' -U postgres

script: "make test"

after_script: coveralls

env:
    - FLASHCUBE_SETTINGS=flashcube.conf.TestingConfig SKIP_FLASHCUBE_CRYPTO=1

notifications:
    email:
        recipients:
            - benjamin@bengfort.com
            - allen.leis@gmail.com
            - spaztick@gmail.com
        on_success: change
        on_failure: change
